# Generated by Django 6.0.6 on 2026-07-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ("title", "created_at"),
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="is_notification_sent",
            field=models.BooleanField(
                choices=[(True, "Да"), (False, "Нет")],
                default=False,
                help_text="Выберите значение",
                verbose_name="Сообщение отправлено",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
