# Generated by Django 6.0.6 on 2026-09-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="is_pablished",
            new_name="is_published",
        ),
    ]
